// @flow
export const SET_ITEM_LIST = 'set item list'
export const ADD_ITEM_LIST = 'add item list'
export const REMOVE_ITEM_LIST = 'remove item list'
export const UPDATE_ITEM_INPUT_CONTENT = 'update item input content'
export const SET_ITEM_EDIT_MODE = 'set item edit mode'
export const MOVE_ITEM = 'move item'
export const SET_FUND_DATA = 'set fund data'
export const UPDATE_FUND_DATA = 'update fund data'
export const CALCULATE_FUND_DATA = 'calculate fund data'
export const ADD_PROJECT_LIST = 'add project list'
export const REMOVE_PROJECT_LIST = 'remove project list'
export const UPDATE_PROJECT_CONTENT = 'update project content'
export const SHOW_INPUT_CONTROL_BAR_INLINE = 'show input control bar inline'
export const HIDE_INPUT_CONTROL_BAR_INLINE = 'hide input control bar inline'
